config/routes.rb
Rails.application.routes.draw do
  root to: 'stocks#top'
  get 'top', to: 'stocks#top'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'}
  resources :stocks do
    collection do
      get '/:id/consumed_edit' => 'stocks#consumed'
      put '/:id/consumed_update' => 'stocks#consumed_update'
    end
  end

  get 'confirm_stocks', to: 'stocks#confirm'
  get 'confirm_update', to: 'stocks#confirm_update'
  put 'update_all', to: 'stocks#update_all'
  delete 'delete_all', to: 'stocks#delete_all'
  
  get 'index_near', to: 'stocks#near'
  get 'index_expire', to: 'stocks#expire'
  get 'index_past', to: 'stocks#past'
  get 'index_favorites', to: 'stocks#favorites'
  get 'index_tags', to: 'stocks#tags'


  get "stock_list/:per" => "stocks#stocks_page"
  get "past_list/:per" => "stocks#past_page"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_rich_text :content
  validates :product_name, length: { maximum: 13 }, presence: true
  # validate :validate_content_length
  # validate :validate_content_attachment_byte_size
  # validate :validate_content_attachments_count
  scope :recent, -> { order(expiration: :asc)}
  now = Date.today
  scope :stocks_near, -> { where('expiration <= ?', Date.today.since(3.month)) }
  scope :stocks_expire, -> { where('expiration <= ?', Date.today) }
  scope :stocks_favorites, -> { where(favorites: true) }
  scope :stocks_tags, -> { where(tags: true) }
  scope :stocks_consumed, -> { where(consumed: true) }
  belongs_to :user


  MAX_CONTENT_LENGTH = 50
  ONE_KILOBYTE = 1024
  MEGA_BYTES = 4
  MAX_CONTENT_ATTACHMENT_BYTE_SIZE = MEGA_BYTES * 1_000 * ONE_KILOBYTE
  MAX_CONTENT_ATTACHMENTS_COUNT = 2

  # images = content.embeds.blobs
  # images = ActiveStorage::Blob

  private
  def validate_content_length
    if content.to_plain_text.length > MAX_CONTENT_LENGTH
      errors.add(:content, :too_long)
    end
  end
  # def validate_content_attachment_byte_size
  #   content.body.attachables.grep(ActiveStorage::Blob).each do |attachable|
  #     if attachable.byte_size > MAX_CONTENT_ATTACHMENT_BYTE_SIZE
  #       errors.add(
  #         :base,
  #         :content_attachable_byte_size_is_oversize,
  #         max_content_attachment_mega_byte_size: MEGA_BYTES,
  #         bytes: attachable.byte_size,
  #         max_bytes: MAX_CONTENT_ATTACHMENT_BYTE_SIZE
  #       )
  #     end
  #   end
  # end
  # def validate_content_attachments_count
  #   if content.body.attachables.grep(ActiveStorage::Blob).count >
  #     MAX_CONTENT_ATTACHMENTS_COUNT
  #       errors.add(
  #         :base, 
  #         :attachment_count_is_too_many,
  #         max_count: MAX_CONTENT_ATTACHMENTS_COUNT
  #       )
  #   end
  # end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :move_to_top, except: :top
  
  def top
    @stocks = Stock.where(id: [1,2,3]).recent
  end

  def index
    @page = 10
    @stocks = Stock.where(consumed: true, user_id: current_user.id).recent.paginate(page: params[:page], per_page: @page)
  end
  
  def stocks_page
    @page = params[:per]
    @stocks = Stock.where(consumed: true, user_id: current_user.id).recent.paginate(page: params[:page], per_page: @page)
    render("stock_list")
  end
  def past
    @page = 10
    @stocks = Stock.where(consumed: false, user_id: current_user.id).recent.paginate(page: params[:page], per_page: @page)
  end

  def past_page
    @page = params[:per]
    @stocks = Stock.where(consumed: false, user_id: current_user.id).recent.paginate(page: params[:page], per_page: @page)
    render("past_list")
  end

  def near
    @stocks = Stock.where(consumed: true, user_id: current_user.id).stocks_near.recent.paginate(page: params[:page], per_page: 5)
  end

  def expire
    @stocks = Stock.where(consumed: true, user_id: current_user.id).stocks_expire.recent.paginate(page: params[:page], per_page: 5)
  end

  def favorites
    @stocks = Stock.where(user_id: current_user.id).stocks_favorites.recent.paginate(page: params[:page], per_page: 5)
  end

  def tags
    @stocks = Stock.where(user_id: current_user.id).stocks_tags.recent.paginate(page: params[:page], per_page: 5)
  end
  
  def consumed
    @stock = Stock.find(params[:id])
  end

  def consumed_update
    @stock = Stock.find(params[:id])
    @stocks.update(consumed: true)
  end

  def new
    @stock = Stock.new
    @user = current_user
  end

  def create
    @stock = Stock.new(stock_params)
    @stock.user_id = current_user.id
    if
      @stock.save
      redirect_to stocks_path
    else
      render "new"
    end
  end

  def show
    @stock = Stock.find(params[:id])
  end

  def edit
    @stock = Stock.find(params[:id])
  end

  def update
    @stock = Stock.find(params[:id])
    if
      @stock.update(stock_params)
      redirect_to stocks_path
    else
      render "edit"
    end
  end

  def destroy
    stock = Stock.find(params[:id])
    stock.destroy
  end

  def confirm
    if params[:edit_all]
      redirect_to confirm_update_path(stocks_ids: params[:stocks_ids])
    elsif params[:delete_all]
      @stocks = Stock.where(id: params[:stocks_ids])
        @stocks.each do |stock|
          stock.destroy
        end
      redirect_to stocks_path
    else params[:consumed]
      @stocks = Stock.where(id: params[:stocks_ids])
      @stocks.update_all(consumed: false)
      redirect_to stocks_path
    end
  end

  def confirm_update
    @stocks = Stock.where(id: params[:stocks_ids])
  end

  def update_all
    stocks = params.permit!.to_h[:stocks]
    stocks.each do |stock|
      stock_db = Stock.find(stock[0])
      stock_db.update!(stock[1])
    end
    redirect_to stocks_path
  end

  private
  def stock_params
    params.require(:stock).permit(:product_name, :expiration, :detail, :open_date, :consumed, :favorites, :tags, :content).merge(user_id: current_user.id)
  end

  def stocks_params
    params.require(:stock).permit(stocks_ids: [:product_name, :expiration, :detail, :open_date, :consumed, :favorites, :tags, :content]).merge(user_id: current_user.id)
  end

  def move_to_top
    redirect_to top_path unless user_signed_in?
  end

end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/layouts/_error_form.html.erb
<% if @stock.errors.any? %>
  <div class = "alert">
    <ul>
      <% @stock.errors.full_messages.each do |message| %>
        <li><i class="fas fa-exclamation"></i><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/stocks/layouts/_form.html.erb
<%= form_tag("/confirm_stocks", method: :get) do %>
<div class="row">
  <% if current_page?(index_near_path) %>
  <div class="col-7">
    <h5>※3ヶ月以内に使い切ってください！</h5>
  </div>
  <% end %>
  <% if current_page?(index_past_path) %>
    <div class="col-5">
    <%= render 'stocks/layouts/list' %>
    </div>
  <% end %>
  <% if current_page?(stocks_path) %>
  <div class="col-5">
    <%= render 'stocks/layouts/list' %>
  </div>
  <% end %>
  <% unless current_page?(index_past_path) %>
  <div class="col-5 ml-auto text-center clipboard">
    <a href="/index_past"><i class="far fa-clipboard"></i><span class="d-non d-sm-inline pl-1">過去のstocks</span></a>
  </div>
  <% end %>
</div>
<div class="stocks">
  <% @stocks.each do |stock| %>
  <ul class="row no-gutters">
    <label class="col-12">
      <div class="product_name">
        <li>
          <div class="sticky">
            <% if stock.favorites %>
            <span class="fas fas-heart btn-sticky-fev1"><%= link_to "お気に入り", stock_path(stock, stock: {favorites: false}), method: :put, class: 'fev' %></span>
            <% else %>
            <span class="fb far-heart btn-sticky-fev0"><%= link_to "add love", stock_path(stock, stock: {favorites: true}), method: :put, class: 'fev' %></span>
            <% end %>

            <% if stock.tags %>
            <span class="fas far-star btn-sticky-tag1"><%= link_to "ふせん", stock_path(stock, stock: {tags: false}), method: :put, class: "tag" %></span>
            <% else %>
            <span class="fc far-star btn-sticky-tag0"><%= link_to "ふせんする", stock_path(stock, stock: {tags: true}), method: :put, class: "tag" %></span>
            <% end %>
          </div>
          <h2 class="check_box"><%= check_box_tag 'stocks_ids[]', stock.id %></h2>
          <h2><%= stock.product_name %></h2>
        </li>
      </div>
      <div class="row justify-content-between border_bg">
        <div class="col-10">
          <li> ｜ 賞味期限 ｜ <%= stock.expiration %> ｜ </li><br />
          <% if stock.open_date.present? %>
          <li> ｜ 開封日 ｜ <%= stock.open_date %> ｜ </li><br />
          <% end %>
          <li> ｜ メーカー・購入店舗等 ｜ <%= stock.detail %></li><br />
          <% if stock.content.present? %>
          <li> ｜ 詳細・メモ ｜ <%= stock.content %></li>
          <% end %>
          <% if stock.consumed %>
            <%= link_to "/stocks/#{stock.id}", method: :get, class: "consumed" do %>
              <i class="fas fa-clipboard"></i> 消費済みにする
            <% end %>
          <% else %>
            <%= link_to "/stocks/#{stock.id}/consumed_edit", method: :get, class: "consumed" do %>
              <i class="far fa-clipboard"></i> 再登録をする
            <% end %>
          <% end %>
        </div>
        <div class="col-1 justify-content-end d-flex align-items-end">
          <div class="btn-group">
            <li class="edit"><%= link_to '編集する', "/stocks/#{stock.id}/edit", method: :get %></li>
            <li class="delete"><%= link_to '削除する', "/stocks/#{stock.id}/", method: :get %></li>
          </div>
        </div>
      </div>
    </label>
  </ul>
  <% end %>
</div>
<%= will_paginate @stocks, class: "page" %>
<div class="btn-group">
  <%= submit_tag "まとめて編集", name: "edit_all", class: "btn btn-outline-info" %>
  <%= submit_tag "まとめて消費済にする", name: 'consumed', class: "btn btn-outline-warning" %>
  <%= submit_tag "一括削除", name: 'delete_all', class: "btn btn-outline-danger" %>
</div>
<% end %>

app/views/stocks/layouts/_header.html.erb
<div class="header">
  <div class="row">
    <div class="col-6">
      <h3><%= current_user.user_name %>さん<a href="/stocks/new" aria-label="在庫登録はこちらから！" title="在庫登録はこちらから">Stocked UP!</a></h3>
    </div>
    <div class=" col-6 text-right">
          <%= button_to 'ログアウト', destroy_user_session_path, method: :delete, :class => "btn-usr" %>
          <% unless current_page?(edit_user_registration_path) %>
            <%= button_to "ユーザー情報編集画面へ", edit_user_registration_path, method: :get, :class => "btn-usr" %>
          <% end %>
    </div>
  </div>
</div>

app/views/stocks/layouts/_list.html.erb
<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    <%= @page %>
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <% if current_page?(stocks_path) %>
    <li><%= link_to(" 5", "/stock_list/5") %></li>
    <li><%= link_to("15", "/stock_list/15") %></li>
    <li><%= link_to("30", "/stock_list/30") %></li>
    <li><%= link_to("50", "/stock_list/50") %></li>
    <% end %>  
    <% if current_page?(index_past_path) %>
    <li><%= link_to(" 5", "/past_list/5") %></li>
    <li><%= link_to("15", "/past_list/15") %></li>
    <li><%= link_to("30", "/past_list/30") %></li>
    <li><%= link_to("50", "/past_list/50") %></li>
    <% end %>
  </ul>
  <label>件ずつ表示する</label>
</div>

app/views/stocks/layouts/_sample.html.erb
<div class="wrap">
  <div class="sample_tab_area">
    <ul class="row nav justify-content-end no-gutters">
      <li class="col-sm-2 nav-item1 justify-content-start"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">あなたの在庫</span></li>
      <li class="col-sm-2 nav-item justify-content-start"><i class="far fa-bell"></i><span class="d-non d-sm-inline pl-1">賞味期限間近</span></li>
      <li class="col-sm-2 nav-item justify-content-start"><i class="fas fa-exclamation-triangle"></i><span class="d-non d-sm-inline pl-1">賞味期限切れ</span></li>
      <li class="col-sm-2 nav-item justify-content-start"><i class="far fa-heart"></i><span class="d-non d-sm-inline pl-1">お気に入り</span></li>
      <li class="col-sm-2 nav-item justify-content-start"><i class="far fa-star"></i><span class="d-non d-sm-inline pl-1">ふせん</span></li>
    </ul>
  </div>
  <div class="panel_area">
    <div class="row">
      <div class="col-5">
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            10
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li> 5</li>
            <li>15</li>
            <li>30</li>
            <li>50</li>
          </ul>
          <label>件ずつ表示する</label>
        </div>
      </div>
      <div class="col-5 ml-auto text-center">
        <span class="d-non d-sm-inline pl-1">過去のstocks</span>
      </div>
    </div>
    <div class="stocks">
      <% @stocks.each do |stock| %>
      <ul class="row no-gutters">
        <label class="col-12">
          <div class="product_name">
            <li>
              <div class="sticky">
                <% if stock.favorites %>
                <span class="fas fas-heart btn-sticky-fev1 fev">お気に入り</span>
                <% else %>
                <span class="fb far-heart btn-sticky-fev0 fev">add love</span>
                <% end %>
                <% if stock.tags %>
                <span class="fas far-star btn-sticky-tag1 tag">ふせん</span>
                <% else %>
                <span class="fc far-star btn-sticky-tag0 tag">ふせんする</span>
                <% end %>
              </div>
              <h2 class="check_box"><%= check_box_tag 'stocks_ids[]', stock.id %></h2>
              <h2><%= stock.product_name %></h2>
            </li>
          </div>
          <div class="row justify-content-between border_bg">
            <div class="col-10">
              <li> ｜ 賞味期限 ｜ <%= stock.expiration %> ｜ </li><br />
              <% if stock.open_date.present? %>
              <li> ｜ 開封日 ｜ <%= stock.open_date %> ｜ </li><br />
              <% end %>
              <li> ｜ メーカー・購入店舗等 ｜ <%= stock.detail %></li><br />
              <% if stock.content.present? %>
              <li> ｜ 詳細・メモ ｜ <%= stock.content %></li>
              <% end %>
              <span class="consumed"><i class="fas fa-clipboard"></i> 消費済みにする</span>
            </div>
            <div class="col-1 justify-content-end d-flex align-items-end">
              <div class="btn-group">
                <li class="edit">編集する</li>
                <li class="delete">削除する</li>
              </div>
            </div>
          </div>
        </label>
      </ul>
      <% end %>
    </div>
    <div class="btn-group">
      <button class='btn btn-outline-info edit_all'>まとめて編集</button>
      <button class='btn btn-outline-warning consumed'>消費済にする</button>
      <button class='btn btn-outline-danger delete_all'>一括削除</button>
    </div>
  </div>
</div>

app/views/stocks/layouts/_sticky.html.erb
<div class="sticky">
	<% if @stock.favorites %>
	<span class="fas fas-heart btn-sticky-fev1"><%= link_to "お気に入り", stock_path(@stock, stock: {favorites: false}), method: :put, class: 'fev' %></span>
	<% else %>
	<span class="fb far-heart btn-sticky-fev0"><%= link_to "add love", stock_path(@stock, stock: {favorites: true}), method: :put, class: 'fev' %></span>
	<% end %>
	<% if @stock.tags %>
	<span class="fas far-star btn-sticky-tag1"><%= link_to "ふせん", stock_path(@stock, stock: {tags: false}), method: :put, class: "tag" %></span>
	<% else %>
	<span class="fc far-star btn-sticky-tag0"><%= link_to "ふせんする", stock_path(@stock, stock: {tags: true}), method: :put, class: "tag" %></span>
	<% end %>
</div>

app/views/stocks/layouts/_tab.html.erb
	<div class="tab_area">
    <ul class="row nav justify-content-end no-gutters">
      <li class="col-sm-2 nav-item1 justify-content-start">
        <i class="far fa-lightbulb"></i>
        <span class="d-non d-sm-inline pl-1">あなたの在庫</span>
      </li>
      <li class="col-sm-2 nav-item justify-content-start">
        <a href="/index_near">
          <i class="far fa-bell"></i>
          <span class="d-non d-sm-inline pl-1">賞味期限間近</span></a>
      </li>
      <li class="col-sm-2 nav-item justify-content-start">
        <a href="/index_expire">
          <i class="fas fa-exclamation-triangle"></i>
          <span class="d-non d-sm-inline pl-1">賞味期限切れ</span></a>
      </li>
      <li class="col-sm-2 nav-item justify-content-start">
        <a href="/index_favorites">
          <i class="far fa-heart"></i>
          <span class="d-non d-sm-inline pl-1">お気に入り</span></a>
      </li>
      <li class="col-sm-2 nav-item justify-content-start">
        <a href="/index_tags">
          <i class="far fa-star"></i>
          <span class="d-non d-sm-inline pl-1">ふせん</span></a>
      </li>
    </ul>
  </div>