config/routes.rb
Rails.application.routes.draw do
  root to: 'stocks#top'
  get 'top', to: 'stocks#top'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'}
  resources :stocks do
    collection do
      get '/:id/consumed_edit' => 'stocks#consumed'
      put '/:id/consumed_update' => 'stocks#consumed_update'
    end
  end

  get 'confirm_stocks', to: 'stocks#confirm'
  get 'confirm_update', to: 'stocks#confirm_update'
  put 'update_all', to: 'stocks#update_all'
  delete 'delete_all', to: 'stocks#delete_all'
  
  get 'index_near', to: 'stocks#near'
  get 'index_expire', to: 'stocks#expire'
  get 'index_past', to: 'stocks#past'
  get 'index_favorites', to: 'stocks#favorites'
  get 'index_tags', to: 'stocks#tags'


  get "stock_list/:per" => "stocks#stocks_page"
  get "past_list/:per" => "stocks#past_page"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_rich_text :content
  validates :product_name, length: { maximum: 13 }, presence: true
  # validate :validate_content_length
  # validate :validate_content_attachment_byte_size
  # validate :validate_content_attachments_count
  scope :recent, -> { order(expiration: :asc)}
  now = Date.today
  scope :stocks_near, -> { where('expiration <= ?', Date.today.since(3.month)) }
  scope :stocks_expire, -> { where('expiration <= ?', Date.today) }
  scope :stocks_favorites, -> { where(favorites: true) }
  scope :stocks_tags, -> { where(tags: true) }
  scope :stocks_consumed, -> { where(consumed: true) }
  belongs_to :user


  MAX_CONTENT_LENGTH = 50
  ONE_KILOBYTE = 1024
  MEGA_BYTES = 4
  MAX_CONTENT_ATTACHMENT_BYTE_SIZE = MEGA_BYTES * 1_000 * ONE_KILOBYTE
  MAX_CONTENT_ATTACHMENTS_COUNT = 2

  # images = content.embeds.blobs
  # images = ActiveStorage::Blob

  private
  def validate_content_length
    if content.to_plain_text.length > MAX_CONTENT_LENGTH
      errors.add(:content, :too_long)
    end
  end
  # def validate_content_attachment_byte_size
  #   content.body.attachables.grep(ActiveStorage::Blob).each do |attachable|
  #     if attachable.byte_size > MAX_CONTENT_ATTACHMENT_BYTE_SIZE
  #       errors.add(
  #         :base,
  #         :content_attachable_byte_size_is_oversize,
  #         max_content_attachment_mega_byte_size: MEGA_BYTES,
  #         bytes: attachable.byte_size,
  #         max_bytes: MAX_CONTENT_ATTACHMENT_BYTE_SIZE
  #       )
  #     end
  #   end
  # end
  # def validate_content_attachments_count
  #   if content.body.attachables.grep(ActiveStorage::Blob).count >
  #     MAX_CONTENT_ATTACHMENTS_COUNT
  #       errors.add(
  #         :base, 
  #         :attachment_count_is_too_many,
  #         max_count: MAX_CONTENT_ATTACHMENTS_COUNT
  #       )
  #   end
  # end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :move_to_top, except: :top
  
  def top
    @stocks = Stock.where(id: [1,2,3]).recent
  end

  def index
    @page = 10
    @stocks = Stock.where(consumed: true, user_id: current_user.id).recent.paginate(page: params[:page], per_page: @page)
  end
  
  def stocks_page
    @page = params[:per]
    @stocks = Stock.where(consumed: true, user_id: current_user.id).recent.paginate(page: params[:page], per_page: @page)
    render("stock_list")
  end
  def past
    @page = 10
    @stocks = Stock.where(consumed: false, user_id: current_user.id).recent.paginate(page: params[:page], per_page: @page)
  end

  def past_page
    @page = params[:per]
    @stocks = Stock.where(consumed: false, user_id: current_user.id).recent.paginate(page: params[:page], per_page: @page)
    render("past_list")
  end

  def near
    @stocks = Stock.where(consumed: true, user_id: current_user.id).stocks_near.recent.paginate(page: params[:page], per_page: 5)
  end

  def expire
    @stocks = Stock.where(consumed: true, user_id: current_user.id).stocks_expire.recent.paginate(page: params[:page], per_page: 5)
  end

  def favorites
    @stocks = Stock.where(user_id: current_user.id).stocks_favorites.recent.paginate(page: params[:page], per_page: 5)
  end

  def tags
    @stocks = Stock.where(user_id: current_user.id).stocks_tags.recent.paginate(page: params[:page], per_page: 5)
  end
  
  def consumed
    @stock = Stock.find(params[:id])
  end

  def consumed_update
    @stock = Stock.find(params[:id])
    @stocks.update(consumed: true)
  end

  def new
    @stock = Stock.new
    @user = current_user
  end

  def create
    @stock = Stock.new(stock_params)
    @stock.user_id = current_user.id
    if
      @stock.save
      redirect_to stocks_path
    else
      render "new"
    end
  end

  def show
    @stock = Stock.find(params[:id])
  end

  def edit
    @stock = Stock.find(params[:id])
  end

  def update
    @stock = Stock.find(params[:id])
    if
      @stock.update(stock_params)
      redirect_to stocks_path
    else
      render "edit"
    end
  end

  def destroy
    stock = Stock.find(params[:id])
    stock.destroy
  end

  def confirm
    if params[:edit_all]
      redirect_to confirm_update_path(stocks_ids: params[:stocks_ids])
    elsif params[:delete_all]
      @stocks = Stock.where(id: params[:stocks_ids])
        @stocks.each do |stock|
          stock.destroy
        end
      redirect_to stocks_path
    else params[:consumed]
      @stocks = Stock.where(id: params[:stocks_ids])
      @stocks.update_all(consumed: false)
      redirect_to stocks_path
    end
  end

  def confirm_update
    @stocks = Stock.where(id: params[:stocks_ids])
  end

  def update_all
    stocks = params.permit!.to_h[:stocks]
    stocks.each do |stock|
      stock_db = Stock.find(stock[0])
      stock_db.update!(stock[1])
    end
    redirect_to stocks_path
  end

  private
  def stock_params
    params.require(:stock).permit(:product_name, :expiration, :detail, :open_date, :consumed, :favorites, :tags, :content).merge(user_id: current_user.id)
  end

  def stocks_params
    params.require(:stock).permit(stocks_ids: [:product_name, :expiration, :detail, :open_date, :consumed, :favorites, :tags, :content]).merge(user_id: current_user.id)
  end

  def move_to_top
    redirect_to top_path unless user_signed_in?
  end

end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/confirm_update.html.erb
<%= render 'stocks/layouts/header' %>
<div class="wrap">
  <div class="tab_area">
    <ul class="row nav justify-content-end no-gutters">
      <li class="col-sm-2 nav-item justify-content-start"><a href="/stocks"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">あなたの在庫</span></a></li>
      <li class="col-sm-2 nav-item1 justify-content-start"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">まとめて編集中</span></li>
    </ul>
  </div>
  <div class="panel_area">
    <div class="stocks">
      まとめて編集画面では詳細登録・編集はできません。
      <%= form_with model: @stocks, url: update_all_path, method: :put do |form| %>
      <% @stocks.each do |stock| %>
      <ul class="row no-gutters">
        <div class="col-12">
          <%= fields_for 'stocks[]', stock do |field| %>
          <div class="product_name">
            <li>
              <div class="sticky">
                <% if stock.favorites %>
                <span class="fas fas-heart btn-sticky-fev1"><%= link_to "お気に入り", stock_path(stock, stock: {favorites: false}), method: :put, class: 'fev' %></span>
                <% else %>
                <span class="fb far-heart btn-sticky-fev0"><%= link_to "add love", stock_path(stock, stock: {favorites: true}), method: :put, class: 'fev' %></span>
                <% end %>
                <% if stock.tags %>
                <span class="fas far-star btn-sticky-tag1"><%= link_to "ふせん", stock_path(stock, stock: {tags: false}), method: :put, class: "tag" %></span>
                <% else %>
                <span class="fc far-star btn-sticky-tag0"><%= link_to "ふせんする", stock_path(stock, stock: {tags: true}), method: :put, class: "tag" %></span>
                <% end %>
              </div>
              <h2><%= field.text_field :product_name, placeholder: '商品名', value: stock.product_name %></h2>
            </li>
          </div>
          <div class="row justify-content-between border_bg">
            <div class="col-10">
              <li>
                <%= field.label :expiration %>
                <%= field.date_field :expiration, placeholder: '賞味期限', value: stock.expiration %>
              </li><br />
              <li>
                <%= field.label :detail %>
                <%= field.text_area :detail, placeholder: 'メーカー・購入店舗等', value: stock.detail %>
              </li><br />
              <li>
                <%= field.label :open_date %>
                <%= field.date_field :open_date, placeholder: '開封日', value: stock.open_date %>
              </li><br />
            </div>
          </div>
        <% end %>
        </div>
      </ul>
    <% end %>
    <%= form.submit 'まとめて更新', :name => "update_all", :class => "btn btn-info" %>
    <% end %>
  </div>
</div>
<a href="/stocks/">Home!</a>

app/views/stocks/consumed.html.erb
<%= render 'stocks/layouts/header' %>
<div class="wrap">
  <div class="tab_area">
    <ul class="row nav justify-content-end no-gutters">
      <li class="col-sm-2 nav-item justify-content-start"><a href="/stocks"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">あなたの在庫</span></a></li>
      <li class="col-sm-2 nav-item1 justify-content-start"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">再登録中</span></li>
    </ul>
  </div>
  <div class="panel_area">
    <div class="stocks">
      <%= render 'error_form' %>
      <ul class="row no-gutters">
        <div class="col-12">
          <%= form_with model: @stock do |form| %>
          <div class="product_name">
            <li>
              <div class="sticky">
                <% if @stock.favorites %>
                <span class="fas fas-heart btn-sticky-fev1"><%= link_to "お気に入り", stock_path(@stock, stock: {favorites: false}), method: :put, class: 'fev' %></span>
                <% else %>
                <span class="fb far-heart btn-sticky-fev0"><%= link_to "add love", stock_path(@stock, stock: {favorites: true}), method: :put, class: 'fev' %></span>
                <% end %>
                <% if @stock.tags %>
                <span class="fas far-star btn-sticky-tag1"><%= link_to "ふせん", stock_path(@stock, stock: {tags: false}), method: :put, class: "tag" %></span>
                <% else %>
                <span class="fc far-star btn-sticky-tag0"><%= link_to "ふせんする", stock_path(@stock, stock: {tags: true}), method: :put, class: "tag" %></span>
                <% end %>
              </div>
              <h2><%= form.text_field :product_name, placeholder: '商品名', value: @stock.product_name %></h2>
            </li>
          </div>
        </div>
        <div class="row justify-content-between border_bg">
          <div class="col-10">
            <li>
              <%= form.label :expiration %>
              <%= form.date_field :expiration, placeholder: '賞味期限', value: @stock.expiration %>
            </li><br />
            <li>
              <%= form.label :open_date %>
              <%= form.date_field :open_date, placeholder: '開封日', value: @stock.open_date %>
            </li><br />
            <li>
              <%= form.label :detail %><br />
              <%= form.text_area :detail, placeholder: 'メーカー・購入店舗等', value: @stock.detail %>
            </li><br />
            <li>
              <%= form.label :content %><br />
              <%= form.rich_text_area :content, placeholder: '詳細・メモ　添付ファイルは2つまで', value: @stock.content %>
            </li>
						<%= form.hidden_field :consumed, :value => true %>
            <%= form.submit "再登録する", class: 'btn-usr' %>
          </div>
        </div>
        <% end %>
    </div>
    </ul>
  </div>
</div>
</div>
<a href="/stocks/">Home!</a>

app/views/stocks/destroy.html.erb
<%= render 'stocks/layouts/header' %>
<div class="wrap">
  <div class="tab_area">
    <ul class="row nav justify-content-end no-gutters">
      <li class="col-sm-2 nav-item justify-content-start"><a href="/stocks"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">あなたの在庫</span></a></li>
      <li class="col-sm-2 nav-item1 justify-content-start"><span class="d-non d-sm-inline pl-1"></span></li>
    </ul>
  </div>
  <div class="panel_area">
    <div class="stocks">
      <ul class="row no-gutters">
        <label class="col-12">
          <div class="row justify-content-between border_bg">
            <div class="col-11 text-center">
              <br />
							<br />
							<br />
							<br />
							<br />
							完全に削除しました。
							<br />
							<br />
							<br />
							<br />
							<br />
            </div>
          </div>
        </label>
      </ul>
    </div>
  </div>
</div>

app/views/stocks/edit.html.erb
<%= render 'stocks/layouts/header' %>
<div class="wrap">
  <div class="tab_area">
    <ul class="row nav justify-content-end no-gutters">
      <li class="col-sm-2 nav-item justify-content-start"><a href="/stocks"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">あなたの在庫</span></a></li>
      <li class="col-sm-2 nav-item1 justify-content-start"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">編集中</span></li>
    </ul>
  </div>
  <div class="panel_area">
    <div class="stocks">
      <%= render 'error_form' %>
      <ul class="row no-gutters">
        <label class="col-12">
        <%= form_with model: @stock do |form| %>
          <div class="product_name">
            <li>
              <%= render 'stocks/layouts/sticky' %>
              <h2><%= form.text_field :product_name, placeholder: '商品名', value: @stock.product_name %></h2>
            </li>
          </div>
        </label>
        <div class="row justify-content-between border_bg">
          <div class="col-11">
            <li>
              <%= form.label :expiration %>
              <%= form.date_field :expiration, placeholder: '賞味期限', value: @stock.expiration %>
            </li><br />
            <li>
              <%= form.label :open_date %>
              <%= form.date_field :open_date, placeholder: '開封日', value: @stock.open_date %>
            </li><br />
            <li>
              <%= form.label :detail %><br />
              <%= form.text_area :detail, placeholder: 'メーカー・購入店舗等', value: @stock.detail %>
            </li><br />
            <li>
              <%= form.label :content %><br />
              <%= form.rich_text_area :content, placeholder: '<詳細・メモ>　添付ファイルは2つまで　　　　　　　　　　　　　　文字入力は右クリックで', value: @stock.content %>
            </li>
          </div>
          <div class="col-11 d-flex justify-content-end align-items-end btn-group">
            <%= form.submit "更新する", class: 'f-btn' %>
          </div>
        </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/stocks/expire.html.erb
<%= render 'stocks/layouts/header' %>
<div class="wrap">
  <div class="tab_area">
    <ul class="row nav justify-content-end no-gutters">
      <li class="col-sm-2 nav-item justify-content-start"><a href="/stocks"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">あなたの在庫</span></a></li>
      <li class="col-sm-2 nav-item justify-content-start"><a href="/index_near"><i class="far fa-bell"></i><span class="d-non d-sm-inline pl-1">賞味期限間近</span></a></li>
      <li class="col-sm-2 nav-item1 justify-content-start"><i class="fas fa-exclamation-triangle"></i><span class="d-non d-sm-inline pl-1">賞味期限切れ</span></li>
      <li class="col-sm-2 nav-item justify-content-start"><a href="/index_favorites"><i class="far fa-heart"></i><span class="d-non d-sm-inline pl-1">お気に入り</span></a></li>
      <li class="col-sm-2 nav-item justify-content-start"><a href="/index_tags"><i class="far fa-star"></i><span class="d-non d-sm-inline pl-1">ふせん</span></a></li>
    </ul>
  </div>
  <div class="panel_area">
    <%= render 'stocks/layouts/form' %>
  </div>
</div>

app/views/stocks/favorites.html.erb
<%= render 'stocks/layouts/header' %>
<div class="wrap">
  <div class="tab_area">
    <ul class="row nav justify-content-end no-gutters">
      <li class="col-sm-2 nav-item justify-content-start"><a href="/stocks"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">あなたの在庫</span></a></li>
      <li class="col-sm-2 nav-item justify-content-start"><a href="/index_near"><i class="far fa-bell"></i><span class="d-non d-sm-inline pl-1">賞味期限間近</span></a></li>
      <li class="col-sm-2 nav-item justify-content-start"><a href="/index_expire"><i class="fas fa-exclamation-triangle"></i><span class="d-non d-sm-inline pl-1">賞味期限切れ</span></a></li>
      <li class="col-sm-2 nav-item1 justify-content-start"><i class="far fa-heart"></i><span class="d-non d-sm-inline pl-1">お気に入り</span></li>
      <li class="col-sm-2 nav-item justify-content-start"><a href="/index_tags"><i class="far fa-star"></i><span class="d-non d-sm-inline pl-1">ふせん</span></a></li>
    </ul>
  </div>
  <div class="panel_area">
    <%= render 'stocks/layouts/form' %>
  </div>
</div>

app/views/stocks/index.html.erb
<%= render 'stocks/layouts/header' %>
<div class="wrap">
  <div class="tab_area">
    <ul class="row nav justify-content-end no-gutters">
      <li class="col-sm-2 nav-item1 justify-content-start"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">あなたの在庫</span></li>
      <li class="col-sm-2 nav-item justify-content-start"><a href="/index_near"><i class="far fa-bell"></i><span class="d-non d-sm-inline pl-1">賞味期限間近</span></a></li>
      <li class="col-sm-2 nav-item justify-content-start"><a href="/index_expire"><i class="fas fa-exclamation-triangle"></i><span class="d-non d-sm-inline pl-1">賞味期限切れ</span></a></li>
      <li class="col-sm-2 nav-item justify-content-start"><a href="/index_favorites"><i class="far fa-heart"></i><span class="d-non d-sm-inline pl-1">お気に入り</span></a></li>
      <li class="col-sm-2 nav-item justify-content-start"><a href="/index_tags"><i class="far fa-star"></i><span class="d-non d-sm-inline pl-1">ふせん</span></a></li>
    </ul>
  </div>
  <div class="panel_area">
    <%= render 'stocks/layouts/form' %>
  </div>
</div>

app/views/stocks/near.html.erb
<%= render 'stocks/layouts/header' %>
<div class="wrap">
  <div class="tab_area">
    <ul class="row nav justify-content-end no-gutters">
      <li class="col-sm-2 nav-item justify-content-start"><a href="/stocks"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">あなたの在庫</span></a></li>
      <li class="col-sm-2 nav-item1 justify-content-start"><i class="far fa-bell"></i><span class="d-non d-sm-inline pl-1">賞味期限間近</span></li>
      <li class="col-sm-2 nav-item justify-content-start"><a href="/index_expire"><i class="fas fa-exclamation-triangle"></i><span class="d-non d-sm-inline pl-1">賞味期限切れ</span></a></li>
      <li class="col-sm-2 nav-item justify-content-start"><a href="/index_favorites"><i class="far fa-heart"></i><span class="d-non d-sm-inline pl-1">お気に入り</span></a></li>
      <li class="col-sm-2 nav-item justify-content-start"><a href="/index_tags"><i class="far fa-star"></i><span class="d-non d-sm-inline pl-1">ふせん</span></a></li>
    </ul>
  </div>
  <div class="panel_area">
    <%= render 'stocks/layouts/form' %>
  </div>
</div>

app/views/stocks/past_list.html.erb
<%= render 'stocks/layouts/header' %>
<div class="wrap">
  <div class="tab_area">
    <ul class="row nav justify-content-end no-gutters">
      <li class="col-sm-2 nav-item justify-content-start"><a href="/stocks"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">あなたの在庫</span></a></li>
      <li class="col-sm-2 nav-item1 justify-content-start"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">過去のstocks</span></li>
    </ul>
  </div>
  <div class="panel_area">
    <%= form_tag("/confirm_stocks", method: :get) do %>
    <div class="row">
        <div class="col-5">
          <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <%= @page %>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to(" 5", "/past_list/5") %></li>
              <li><%= link_to("15", "/past_list/15") %></li>
              <li><%= link_to("30", "/past_list/30") %></li>
              <li><%= link_to("50", "/past_list/50") %></li>
            </ul>
          <label>件ずつ表示する</label>
        </div>
      </div>
    </div>
    <div class="stocks">
      <% @stocks.each do |stock| %>
      <ul class="row no-gutters">
        <label class="col-12">
          <div class="product_name">
            <li>
              <div class="sticky">
                <% if stock.favorites %>
                <span class="fas fas-heart btn-sticky-fev1"><%= link_to "お気に入り", stock_path(stock, stock: {favorites: false}), method: :put, class: 'fev' %></span>
                <% else %>
                <span class="fb far-heart btn-sticky-fev0"><%= link_to "add love", stock_path(stock, stock: {favorites: true}), method: :put, class: 'fev' %></span>
                <% end %>

                <% if stock.tags %>
                <span class="fas far-star btn-sticky-tag1"><%= link_to "ふせん", stock_path(stock, stock: {tags: false}), method: :put, class: "tag" %></span>
                <% else %>
                <span class="fc far-star btn-sticky-tag0"><%= link_to "ふせんする", stock_path(stock, stock: {tags: true}), method: :put, class: "tag" %></span>
                <% end %>
              </div>
              <h2 class="check_box"><%= check_box_tag 'stocks_ids[]', stock.id %></h2>
              <h2><%= stock.product_name %></h2>
            </li>
          </div>
          <div class="row justify-content-between border_bg">
            <div class="col-10">
              <li> ｜ 賞味期限 ｜ <%= stock.expiration %> ｜ </li><br />
              <% if stock.open_date.present? %>
              <li> ｜ 開封日 ｜ <%= stock.open_date %> ｜ </li><br />
              <% end %>
              <li> ｜ メーカー・購入店舗等 ｜ <%= stock.detail %></li><br />
              <% if stock.content.present? %>
              <li> ｜ 詳細・メモ ｜ <%= stock.content %></li>
              <% end %>
              <% if stock.consumed %>
                <%= link_to(content_tag(:i, ' 消費済みにする', class: 'fas fa-clipboard'), "/stocks/#{stock.id}", method: :get, class: "consumed") %>
              <% else %>
                <%= link_to(content_tag(:i, ' 再登録をする', class: 'far fa-clipboard'), "/stocks/#{stock.id}/consumed_edit", method: :get, class: "consumed") %>
              <% end %>
            </div>
            <div class="col-1 justify-content-end d-flex align-items-end">
              <div class="btn-group">
                <li class="edit"><%= link_to '編集する', "/stocks/#{stock.id}/edit", method: :get %></li>
                <li class="delete"><%= link_to '削除する', "/stocks/#{stock.id}/", method: :get %></li>
              </div>
            </div>
          </div>
        </label>
      </ul>
      <% end %>
    </div>
    <%= will_paginate @stocks, class: "page" %>
    <div class="btn-group">
    <%= submit_tag "まとめて編集", name: "edit_all", class: "btn btn-outline-info" %>
    <%= submit_tag "まとめて消費済にする", name: 'consumed', class: "btn btn-outline-warning" %>
    <%= submit_tag "一括削除", name: 'delete_all', class: "btn btn-outline-danger" %>
    </div>
  <% end %>
  </div>
</div>

app/views/stocks/show.html.erb
<%= render 'stocks/layouts/header' %>
<div class="wrap">
  <div class="tab_area">
    <ul class="row nav justify-content-end no-gutters">
      <li class="col-sm-2 nav-item justify-content-start"><a href="/stocks"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">あなたの在庫</span></a></li>
      <li class="col-sm-2 nav-item1 justify-content-start"><i class="far fa-lightbulb"></i><span class="d-non d-sm-inline pl-1">確認画面</span></li>
    </ul>
  </div>
  <div class="panel_area">
    <div class="stocks">
      <ul class="row no-gutters">
        <label class="col-12">
          <div class="product_name">
            <li>
              <%= render 'stocks/layouts/sticky' %>
              <h2><%= @stock.product_name %></h2>
            </li>
          </div>
          <div class="row justify-content-between border_bg">
            <div class="col-11">
              <li> ｜ 賞味期限 ｜ <%= @stock.expiration %> ｜ </li><br />
              <% if @stock.open_date.present? %>
              <li> ｜ 開封日 ｜ <%= @stock.open_date %> ｜ </li><br />
              <% end %>
              <li> ｜ メーカー・購入店舗等 ｜ <%= @stock.detail %></li><br />
              <li> ｜ 詳細・メモ ｜ <%= @stock.content %></li>
            </div>
            <div class="col-11 d-flex justify-content-end align-items-end btn-group">
              <% if @stock.consumed == false %>
                <li class="show_consumed"><%= link_to "再度在庫にする", stock_path(@stock, stock: {consumed: true}), method: :put %></li>
              <% else %>
                <li class="show_consumed"><%= link_to "消費済みにする", stock_path(@stock, stock: {consumed: false}), method: :put %></li>
              <% end %>
              <li class="show_delete"><%= link_to "削除 (今後購入しない場合)", "/stocks/#{@stock.id}/", method: :delete %></li>
            </div>
          </div>
        </label>
      </ul>
    </div>
  </div>
</div>

app/views/stocks/test.html.erb
<div class="content">
  <div>
    <a href="/stocks/new">Get Stocked!</a>
    <%= form_with model: @stocks, url: update_all_path, method: :put do |form| %>
      <% @stocks.each do |stock| %>
        <%= fields_for 'stocks[]', stock do |field| %>
        <ul>
          <li>
            <%= field.label :product_name %>
            <%= field.text_field :product_name, placeholder: '商品名', value: stock.product_name %>
          </li>
          <li>
            <%= field.label :expiration %>
            <%= field.date_field :expiration, placeholder: '賞味期限', value: stock.expiration %>
          </li>
          <li>
            <%= field.label :detail %>
            <%= field.text_area :detail, placeholder: '詳細・メモ', value: stock.detail %>
          </li>
          <li>
            <%= field.label :open_date %>
            <%= field.date_field :open_date, placeholder: '開封日', value: stock.open_date %>
          </li> 

        </ul>
        <% end %>
      <% end %>
      <%= form.submit '一括編集', :name => "update_all" %>
    <% end %>
  </div>
</div>